import { assets } from "../assets/assets";
import { motion } from "framer-motion";
const Header = () => {
  return (
    <motion.div className="flex flex-col justify-center items-center text-center my-20 ">
      <div className="text-stone-500 inline-flex text-center gap-2 bg-white px-6 py-1 rounded-full border border-neutral-500">
        <p>Best Text to Image generator.</p>
        <img src={assets.star_icon} alt="star_icon" />
      </div>
      {/* Heading */}
      <h1 className="text-4xl max-w-[300px] sm:text-7xl sm:max-w-[590px] mx-auto  mt-10 text-center">
        Turn text to <span className="text-blue-500">image</span> in seconds.
      </h1>
      <p className="text-center max-w-xl mx-auto mt-5">
        Unleash you creativity with AI. <br /> Turn your imagination into
        downloadable images in seconds- just prompt and watch the magic
        happen...
      </p>
      <button className="sm:text-lg text-white bg-black w-auto mt-8 px-12 py-2.5 flex items-center gap-2 rounded-full">
        Generate Images <img className="h-6" src={assets.star_group} alt="" />
      </button>

      <div className="flex gap-2 justify-center mt-6">
        {Array(6)
          .fill("")
          .map((item, index) => {
            return (
              <img
                className="rounded hover:scale-105 transition-all duration-300 cursor-pointer max-sm:w-10"
                src={
                  index % 2 === 0 ? assets.sample_img_1 : assets.sample_img_2
                }
                alt=""
                key={index}
                width={70}
              />
            );
          })}
      </div>
      <p className="mt-2 text-neutral-600">
        images generated by <span className="text-blue-600">imagfiy</span>
      </p>
    </motion.div>
  );
};

export default Header;
